### PR TITLE
Add check column to ChangesBrowser2

### PR DESCRIPTION
**Pull request by Lin777**
And change the textArea to diffPresenter
image

### CODE REVIEW

**Comment by CafeKrem** [comment]
Sorry the CI isn't fully functional. I will fix it.
In initializePresenter 
you do this : 
`table
		whenSelectionChangedDo:
			[ :item | item ifNotNil: [ self buildDiffFor: 
				(item widget items at: (item selectedIndex))] ]`

 why this  (item widget items at: (item selectedIndex)) ? item is your selectedElement.
I think you must write  :
`self buildDiffFor: item`

**Comment by CafeKrem** [comment]
sorry but I compare ChangeBrowser and SycRefactoringPreview that I show is that those two are really similar you can merge both use the diffPresenter(it's a good idea I don't know this widget thanks)  into SycRefactoringPreview and write another defaultSpec in SycRefactoringPreview,  if you have time with that we will only have 1 class to test. if you have no time tell me I will do it.

**Comment by CafeKrem** [comment]
if you have any question don't hesitate.

**Comment by Lin777** [comment]
Of course, then I will review initializePresenter according to your suggestion and also SycRefactoringPreview today

**Comment by CafeKrem** [comment]
Perfect, thank you

**Comment by CafeKrem** [comment]
finally, for the moment, we don't merge ChangeBrowser and SycRefactoringPreview

**Pull request closed without merging**
